shopkart/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cartapp'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('', views.cart_detail, name="cart_detail"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/', views.full_remove, name="full_remove"),

]

shopkart/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'

urlpatterns=[
    path('',views.SearchResult,name="SearchResult"),
]

shopkart/shopapp/urls.py
from django.urls import path
from . import views

app_name = 'shopapp'

urlpatterns = [
    path('', views.AllProductCat, name="allprocat"),
    path('<slug:c_slug>/', views.AllProductCat, name="product_by_category"),
    path('<slug:c_slug>/<slug:p_slug>/', views.proDetail, name="productdetail"),
]

shopkart/shopkart/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shopapp.urls')),
    path('/search/',include('searchapp.urls')),
    path('/cart/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopkart/cartapp/models.py
from django.db import models
from shopapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shopkart/searchapp/models.py
from django.db import models

# Create your models here.

shopkart/shopapp/models.py
from django.db import models
from django . urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_urls(self):
        return reverse('shopapp:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def get_url (self):
        return reverse('shopapp:productdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

shopkart/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
        return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')


def cart_detail(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product= get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

shopkart/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q


# Create your views here.

def SearchResult(request):
    product = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        product = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'product': product})

shopkart/shopapp/views.py
from .models import Category, Product
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def AllProductCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(Paginator.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product': product})

shopkart/templates/base.html
{%load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.css' %}">
</body>
</html>

shopkart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is cart page.Proceed to review your item and place the order

{% endblock %}
{% block title %}
The Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center my_prod_title">Your shopping cart is empty</h1><br>
        <p class="text-center">Please click <a href="{% url 'shopapp:allprocat' %}">ShopKart</a> to continue shopping.</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center"><br>
        <h1 class="text-center my_title">Your shopping cart</h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_cus_table">
            <thead class="my_cus_head">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a  href="cart_item.product.get_absolute_url"><img
                            src="{{cart_item.product.image.url}}"
                            alt="no image"
                            class="float-left rounded custom_image"> </a>
                </td>
                <td class="text-left">{{cart_item.product.name}}<br>
                    SKU: {{cart_item.product.id}}<br>
                    price: ₹ {{cart_item.product.price}}<br>
                    qty: {{cart_item.quantity}} x ₹ {{cart_item.product.price}}
                </td>
                <td>
                    ₹ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a">
                        <i class="fa fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"> <i
                        class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon"> <i
                        class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"> <i
                        class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon"> <i
                        class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_cus_table">
            <thead class="my_cus_head">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <td>
                    <b>Please review your shop Cart items before proceeding with the order payment.<b>
                </td>
            </tr>
            <tr>
                <td class="text-left">Your Total is : <strong>{{total}}</strong>

                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:allprocat' %}" class="btn btn-success btn-block my_cus_button">Continue
                Shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

shopkart/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{category.description|truncatewords:155}}
{% else %}
ShopKart
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{category.name}}-ShopKart
{% else %}
See more collection
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
{% csrf_token %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
            <!--            <p><a href="{% url 'shopapp:allprocat' %}">Our Product </a></p>-->
        </div>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="1500px" height="845px"><br><br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1><br>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/SHOPKART.png' %}" alt="Our Products" width="1500px"
             height="645px">
        <h5 class="text-center my_title">Our Products</h5>
        <p class="text-center desc"> Online shopping is a form of electronic commerce which allows consumers to directly
            buy goods or services from a seller over the Internet using a web browser or a mobile app. Consumers find a
            product of interest by visiting the website of the retailer directly or by searching among alternative
            vendors using a shopping search engine, which displays the same product's availability and pricing at
            different e-retailers. As of 2020, customers can shop online using a range of different computers and
            devices, including desktop computers, laptops, tablet computers and smartphones.</p><br><br>
    </div>
    {% endif %}
</div>
<div>
    <div>
        <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{product.get_url}}"> <img class="card-img-top my_image"
                                                            src="{{product.image.url}}" alt="{{product.name}}"
                                                            width="350px"
                                                            height="400px"> </a>
                        <div>
                            <div class="card-body">
                                <h4>{{product.name}}</h4>
                                <p>{{product.description}}</p>
                                <p>₹ {{product.price}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}"
                       class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

shopkart/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy;ShopKart PVT LMT. All rights reserved.</p>
</div>

shopkart/templates/header.html
{% load static %}
<header>
      <a href="{% url 'shopapp:allprocat' %}"> <img src="{% static 'img/logo.png' %}" alt="logoimg" width="150" height="150px"></a>
</header>

shopkart/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/"><i class="fa fa-" >ShopKart</i>
</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:allprocat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_urls}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get" role="search">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i>
</button>
      </form>
    </div>
  </div>
</nav>

shopkart/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
{% if category %}
{{product.name}}-ShopKart
{% endif %}
{% endblock %}
{% block content %}
{% csrf_token %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allprocat' %}">HOME</a>| <a
                href="{{product.category.get_url}}">{{product.category}}</a>| {{product.name}} </p>
    </div>
</div>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{product.image.url}}" alt="{{product.name}}" width="555px" height="665">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>₹ {{product.price}}</p>
                <p class="my_prod_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <p class="my_prod_text"><b>Out of Stock</b></p>
                {% else %}
                <a class="btn btn-warning" href="{% url 'cartapp:add_cart' product.id %}">Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

shopkart/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

We have veriety products

{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}

<div><p class="text-center my_search_text">You have search for:<b>"{{query}}"</b></p></div>
<div class="container">
    <div class="row mx_auto">
        {% for product in product %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"> <img class="card-img-top my_image"
                                                    src="{{product.image.url}}" alt="{{product.name}}"
                                                    width="350px"
                                                    height="400px"> </a>
                <div>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.description}}</p>
                        <p>₹ {{product.price}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}